Second run producing artifacts

diff --git a/.github/workflows/acceptance.yml b/.github/workflows/acceptance.yml
--- a/.github/workflows/acceptance.yml
+++ b/.github/workflows/acceptance.yml
@@ -322,7 +322,7 @@ jobs:
       - name: Check for failures
         if: contains(needs.*.result, 'failure')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent  jobs have failed. You may need to re-run it." && exit 1
 
       - name: Diff snapshots
         id: visual-snapshots-diff
